[project]
name = "sprinkle"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain>=0.3.26",
    "langchain-google-genai>=1.0.0",
    "pydantic>=2.11.7",
]

[tool.pyright]
venvPath = ".venv"
venv = "."
